config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
	attributes :name,  		:validate => true
  attributes :email, 		:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message, 	:validate => true
  attributes :nickname, :captcha => true

  def headers 
  	{
  		:subject => "Contact Form",
  		:to => "jeffrey.aschenbrenner@gmail.com",
  		:from => %("#{name}" <#{email}>)
  	}
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
	friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new 
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 10)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params
		if @post.save
			redirect_to @post, notice: "Hellz yeah, Jeff! Your article was successfully saved!"
		else
			render 'new', notice: "Oh no, Jeff! I was unable to save your post."	
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "Huzzah! Your article was successfully saved!"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug)
	end

	def find_post 
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@projects = Project.all.order("created_at desc")
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "Nice Jeff! That project was successfully saved!"
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "Nice Jeff! That project was successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private

	def find_project
		@project = Project.friendly.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
		@projects = Project.all.limit(3).order("created_at desc")
		@contact = Contact.new 
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message.'
			render :new
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h3>Thank you for your message!</h3>
        <p>I'll get back to you soon.
      </div>
    </div> 
  </div>
</section>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name, required: true %>

		<%= f.label :email %>
		<%= f.email_field :email, required: true %>

		<%= f.label :message %>
		<%= f.text_area :message, as: :text %>

		<div class="hidden">
			<%= f.label :nickname %>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div>

		<%= f.submit 'Send Message', class: "button" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Jeff Aschenbrenner</title>
		
	<link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'Jeff Aschenbrenner', root_path(:anchor => 'page-top'), :class => 'navbar-brand' %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>                    
                    <li>
                    	<%= link_to 'About', root_path(:anchor => 'about'), :class => 'page-scroll' %>
                    </li>
                    <li>
                    	<%= link_to 'Projects', root_path(:anchor => 'projects-blog'), :class => 'page-scroll' %>
                    </li>
                    <li>
                    	<%= link_to 'Blog', root_path(:anchor => 'projects-blog'), :class => 'page-scroll' %>
                    </li>
                    <li>
                    	<%= link_to 'Contact', root_path(:anchor => 'contact'), :class => 'page-scroll' %>
                    </li>
                    <% if user_signed_in? %>
                        
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li>
                                <%= link_to "Create Post", new_post_path %>
                            </li>
                            <li>
                                <%= link_to "Create Project", new_project_path %>
                                
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                            </li>
                          </ul>
                        </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <% if notice %>
        <div class="alert alert-info alert-dismissible text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
        <!-- <p class="alert alert-info"><%= notice %></p> -->
    <% elsif alert %>           
        <div class="alert alert-danger alert-dismissible text-center" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
        <!-- <p class="alert alert-danger"><%= alert %></p> -->
    <% end %>   


    <%= yield %>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center copyright">
                    Copyright &copy; 2015 Jeff Aschenbrenner
                </div>
                <div class="col-md-6 text-center">
                    <ul class="list-inline">
                        <li>
                            <a href="http://twitter.com/jeffasch" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="http://github.com/jeffaschenbrenner" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-github"></i></a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/pub/jeffrey-aschenbrenner/38/a31/27b" target="_blank" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

</body>

</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'jeffaschenbrenner';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();

    var reset = function (newIdentifier, newUrl, newTitle, newLanguage) {
        DISQUS.reset({
            reload: true,
            config: function () {
                this.page.identifier = newIdentifier;
                this.page.url = newUrl;
                this.page.title = newTitle;
                this.language = newLanguage;
            }
        });
    };
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevent this post from saving:</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, :class => 'form-control', :placeholder => 'Title' %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <%= f.label :content %>
      <%= f.text_area :content, :class => 'form-control', :placeholder => 'Content' %>
    </div>
  </div>
  <br>
  <div id="success"></div>
  <div class="row">
      <div class="form-group col-xs-12">
        <%= f.submit "Create Post", :class => "btn btn-success btn-lg" %>
      </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<section id="post">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Edit Post</h2>
        <hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/posts/index.html.erb
<section id="posts">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Blog</h2>
        <hr class="star-primary">
        <% @posts.each do |post| %>
            <div class="row text-center">
                <div class="col-lg-12">
                    <p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>                                    	
                    <h3><%= link_to post.title, post %></h3>
                </div>      
            </div>
            <div class="row text-left">
            	<div class="col-lg-8 col-lg-offset-2">
            		<p><%= markdown truncate(post.content, :length => 225) %></p>
            		<p class="text-center"><%= link_to "Read More", post %></p>
            	</div>
            </div>
            <hr class="content-divider">
        <% end %>		
        <div class="row">
            <div class="col-lg-12 text-center">
                <%= will_paginate @posts %>
            </div>
        </div>
			</div>
		</div>
	</div>
</section>

app/views/posts/new.html.erb
<section id="project">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>New Post</h2>
        <hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/posts/show.html.erb
<section id="post">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2><%= @post.title %></h2>
				<p class="date"><%= @post.created_at.strftime("%A, %b, %d") %></p>
        <hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<div class="article">
					<%= markdown @post.content%>										
				</div>
				<% if user_signed_in? %>
					<div class="admin-links">
						<%= link_to "Edit", edit_post_path(@post) %>
						<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
					</div>
				<% end %>
			</div>			
		</div>
		<hr class="content-divider">						
		<div class="row">
			<div class="col-lg-12 text-center">
				<p>Share <%= @post.title %></p>
				<!-- Twitter -->
				<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @jeffasch - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200 left=300');void(0);" class="btn-social"><i class="fa fa-fw fa-twitter"></i></a>
				<!-- Facebook -->
				<a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200 left=300');void(0);" class="btn-social"><i class="fa fa-facebook"></i></a>
				<!-- Google Plus -->
				<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200 left=300');void(0);" class="btn-social"><i class="fa fa-google-plus"></i></a>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<%= render 'disqus' %>
			</div>
		</div>
	</div>
</section>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error") %> prevent this project from saving:</h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, :class => 'form-control', :placeholder => 'Title' %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <%= f.label :description %>
      <%= f.text_area :description, :class => 'form-control', :placeholder => 'Description' %>
    </div>
  </div>
  <div class="row control-group">
    <div class="form-group col-xs-12 floating-label-form-group controls">
      <%= f.label :link %>
      <%= f.text_field :link, :class => 'form-control', :placeholder => 'Link' %>
    </div>
  </div>
  <br>
  <div id="success"></div>
  <div class="row">
      <div class="form-group col-xs-12">
        <%= f.submit "Create Project", :class => "btn btn-success btn-lg" %>
      </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<section id="project">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Edit Project</h2>
        <hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/projects/index.html.erb
<section id="projects-all">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>Projects</h2>
        <hr class="star-primary">
        <% @projects.each do |project| %>
            <div class="row text-center">
                <div class="col-lg-12">
                    <p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>                                    	
                    <h3><%= link_to project.title, project %></h3>
                </div>      
            </div>
            <div class="row text-left">
            	<div class="col-lg-8 col-lg-offset-2">
            		<p><%= markdown truncate(project.description, :length => 225) %></p>
            		<div class="article-actions">
            			<%= link_to "Read More", project %>
            			<a href="<%= project.link %>" class="project_button" target="_blank">Visit <%= project.title %></a>
            		</div>
            	</div>
            </div>
            <hr class="content-divider">
        <% end %>		
			</div>
		</div>
	</div>
</section>

app/views/projects/new.html.erb
<section id="project">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2>New Project</h2>
        <hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-12">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</section>

app/views/projects/show.html.erb
<section id="project">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h2><%= @project.title %></h2>
				<p class="date"><%= @project.created_at.strftime("%A, %b, %d") %></p>
        <hr class="star-primary">
			</div>
		</div>
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<div class="article">
					<%= markdown @project.description%>										
				</div>
				<div class="project-link">
					<a href="<%= @project.link %>" class="btn btn-lg btn-outline" target="_blank">Visit <%= @project.title %></a>
				</div>
				<% if user_signed_in? %>
					<div class="admin-links">
						<%= link_to "Edit", edit_project_path(@project) %>
						<%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure?" } %>
					</div>
				<% end %>
			</div>			
		</div>
	</div>
</section>

app/views/welcome/index.html.erb
<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <img class="img-responsive img-circle" src="<%= asset_path('profile.png') %>" alt="">
                <div class="intro-text">
                    <span class="name">Jeff</span>
                    <span class="name">Aschenbrenner</span>
                    <hr class="star-light">
                    <span class="skills">Web Developer</span>
                </div>
            </div>
        </div>
    </div>
</header>

<!-- About Section -->
<section id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>About</h2>
                <hr class="star-primary">                
            </div>
            <div class="col-lg-6 col-lg-offset-3">
                <p>Hey, I'm Jeff! I am a full stack developer living in Plano, Texas.</p>
                <p>I am constantly improving my knowledge in web technologies and am currently sharpening my skills in the <a href="http://www.rubyonrails.org" target="_blank">Ruby on Rails framework</a> to facilitate the creation of amazing applicaitons.</p>
                <p>You can follow my random interests and thoughts on <a href="http://twitter.com/jeffasch" target="_blank">twitter</a> and see some of my code on <a href="http://github.com/jeffaschenbrenner" target="_blank">Github</a>.</p>
            </div>
        </div>
    </div>
</section>

<!-- Portfolio / Blog Section -->
<section class="success" id="projects-blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 text-center">
                <h2>Projects</h2>
                <hr class="star-light">
                <% @projects.each do |project| %>
                    <div class="row text-center">
                        <div class="col-lg-12">
                            <h3><%= link_to project.title, project %></h3>
                            <p class="date"><%= project.created_at.strftime("%A, %b, %d") %></p>
                        </div>      
                    </div>
                <% end %>
                <div class="row text-center">
                    <div class="col-lg-12">
                       <%= link_to "View All Projects", projects_path, :class => "btn btn-lg btn-outline" %>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 text-center">
                <h2>Blog</h2>
                <hr class="star-light">
                <% @posts.each do |post| %>
                    <div class="row text-center">
                        <div class="col-lg-12">
                            <h3><%= link_to post.title, post %></h3>
                            <p class="date"><%= post.created_at.strftime("%A, %b, %d") %></p>
                        </div>      
                    </div>
                <% end %>
                <div class="row text-center">
                    <div class="col-lg-12">
                       <%= link_to "View All Posts", posts_path, :class => "btn btn-lg btn-outline" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Contact Section -->
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Contact Me</h2>
                <hr class="star-primary">
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <%= form_for @contact do |f| %>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <%= f.label :name %>
                        <%= f.text_field :name, required: true, :class => "form-control", :placeholder => "Name" %>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <%= f.label :email %>
                        <%= f.email_field :email, required: true, :class => "form-control", :placeholder => "Email" %>
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                        <%= f.label :message %>
                        <%= f.text_area :message, as: :text, :class => "form-control", :placeholder => "Message" %>
                    </div>
                </div>
                <div class="hidden">
                    <%= f.label :nickname %>
                    <%= f.text_field :nickname, hint: 'leave this field blank' %>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <%= f.submit 'Send Message', :class => "btn btn-success btn-lg" %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</section>